version: '3.2'
services:
  gw:
    build:
      context: ./federation2.0
      dockerfile: Dockerfile
    restart: unless-stopped
    command: node src/index.js
    ports:
      - 8200:8200
    depends_on:
      - schema_registry
    environment:
      PORT: 8200
      SCHEMA_REGESTRY_HOST: schema_registry
      SCHEMA_REGESTRY_PORT: 8310
      SCHEMA_REGESTRY_URL: '/schema'

  schema_registry:
    build:
      context: ./schema_registry
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c "alembic upgrade head && python app.py"
    ports:
      - 8310:8310
    depends_on:
      - db
    environment:
      ENV_FOR_DYNACONF: local
      PORT: 8310
      POSTGRES__host: db
      POSTGRES__port: 5432
      POSTGRES__user: postgres
      POSTGRES__password: postgres
      POSTGRES__database: schema_registry

  service1:
    build:
      context: ./serv1
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c "python app.py"
    environment:
      PORT: 8302
      NGINX_PORT: 8301
      HOSTN: nginx
      NAME: service1
      ENDPOINT: '/service1'
      S_HOST: schema_registry
      S_PORT: 8310
      S_ENDPOINT: 'graphql'
    ports:
      - 8302-8305
    depends_on:
      - schema_registry

  service2:
    build:
      context: ./serv2
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c "python app.py"
    environment:
      PORT: 8312
      NGINX_PORT: 8301
      HOSTN: nginx
      NAME: service2
      ENDPOINT: '/service2'
      S_HOST: schema_registry
      S_PORT: 8310
      S_ENDPOINT: 'graphql'
    ports:
      - 8312-8315
    depends_on:
      - schema_registry
  service3:
    build:
      context: ./serv3
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c "python app.py"
    environment:
      PORT: 8322
      NGINX_PORT: 8301
      HOSTN: nginx
      NAME: service3
      ENDPOINT: '/service3'
      S_HOST: schema_registry
      S_PORT: 8310
      S_ENDPOINT: 'graphql'
    ports:
      - 8322-8325
    depends_on:
      - schema_registry

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    ports:
      - 50004:5432
    environment:
      POSTGRES_DB: schema_registry
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  nginx:
      image: nginx:1.18.0-alpine
      ports:
      - 8301
      volumes:
        - ./default.conf:/etc/nginx/conf.d/default.conf
      depends_on:
        - gw
        - service2
        - service1