default:
  NAME: SCHEMA_REGISTRY
  HOST: schema-registry
  PORT: 8310
  SERVICE_OPERATIONS: ['_entities', '_service']

  DEBUG: false

  DATABASE_SCRIPT:
    backup_db: false
    drop_db: false
    use_alembic: true
    create_postgis: false

  POSTGRES:
    driver: asyncpg
    host: localhost
    port: 5432
    user: postgres
    password: postgres
    database: schema_registry
    echo: false
    pool_min_size: 1
    pool_max_size: 16
    ssl: false
    retry_limit: 32
    retry_interval: 1

  LOG:
    format: '%(levelname)-8s# %(filename)s[LINE:%(lineno)d] [%(asctime)s.%(msecs)d]: %(message)s'
    level: INFO

testing:
  DEBUG: true
  POSTGRES:
    driver: asyncpg
    host: db_schema_registry
    port: 5432
    user: postgres
    password: postgres
    database: test_db
    echo: false
    pool_min_size: 1
    pool_max_size: 16
    ssl: false
    retry_limit: 32
    retry_interval: 1
